services:
  api:
    build:
      context: .
      dockerfile: Core/BookStore.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development

      ConnectionStrings__DefaultConnection: >
        Server=sqlserver;Database=BookStoreDb;
        User Id=sa;Password=${SA_PASSWORD};
        TrustServerCertificate=True

      JwtOptions__Key: ${JWT_SECRET}
      JwtOptions__Issuer: BookStoreAPI
      JwtOptions__Audience: BookStoreClient
      JwtOptions__ExpiryInMinutes: 60

      MinIO__Endpoint: minio:9000
      MinIO__AccessKey: ${MINIO_ACCESS}
      MinIO__SecretKey: ${MINIO_SECRET}
      MinIO__BucketName: ${MINIO_BUCKET}
      MinIO__UseSSL: false

      AppOptions__EnableSeed: "true"

    ports:
      - "5000:8080"

  sqlserver:
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${SA_PASSWORD}

  minio:
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET}
    ports:
      - "9000:9000"
      - "9090:9090"
