
services:
  api:
    image: localhost:5000/bookstore/api:latest
    container_name: bookstore-api
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production

      ConnectionStrings__DefaultConnection: >
        Server=sqlserver;Database=BookStoreDb;
        User Id=sa;Password=${SA_PASSWORD};
        TrustServerCertificate=True

      JwtOptions__Key: ${JWT_SECRET}
      JwtOptions__Issuer: BookStoreAPI
      JwtOptions__Audience: BookStoreClient
      JwtOptions__ExpiryInMinutes: 60

      MinIO__Endpoint: minio:9000
      MinIO__AccessKey: ${MINIO_ACCESS}
      MinIO__SecretKey: ${MINIO_SECRET}
      MinIO__BucketName: ${MINIO_BUCKET}
      MinIO__UseSSL: false

      AppOptions__EnableSeed: "false"

    depends_on:
      - sqlserver
      - minio

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: bookstore-sql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${SA_PASSWORD}
    volumes:
      - sql_data:/var/opt/mssql

  minio:
    image: minio/minio
    container_name: bookstore-minio
    command: server /data --console-address ":9090"
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET}
    volumes:
      - minio_data:/data

volumes:
  sql_data:
  minio_data:
